version: "3.3"
services:
  redis:
    image: redis:7-alpine
    restart: always
    container_name: android-static-redis
  android-static-backend:
    build: .
    restart: always
    container_name: android-static-backend
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8010:8010"
  queue-wrapper:
    build: ./queue_wrapper
    restart: always
    container_name: android-static-wrapper
    ports:
      - "5001:5001"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - redis
      - android-static-backend
  celery-worker:
    build: ./queue_wrapper
    restart: always
    command: celery -A tasks worker --loglevel=info --concurrency=1
    environment:
      - ANDROGUARD_BASE=http://android-static-backend:8010
      - REDIS_URL=redis://redis:6379/0
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PDF_API=http://192.168.50.53:15148/api/report
    depends_on:
      - redis
      - android-static-backend
networks:
  default:
    external:
      name: app-sso-network
